<?
/*********************************************************************************************************
 This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Informazioni File";
  $msg['name']          = "Nome";
  $msg['size']          = "Dimensione";
  $msg['lastChange']    = "Ultima Modifica";
  $msg['owner']         = "Proprietario";
  $msg['group']         = "Gruppo";
  $msg['other']         = "Altro";
  $msg['read']          = "Lettura";
  $msg['write']         = "Scrittura";
  $msg['execute']       = "Esecuzione";
  $msg['permissions']   = "Permessi";
  $msg['error']         = "ERRORE";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Reset";
  $msg['cmdSave']       = "Salva";
  $msg['cmdViewList']   = "Torna all'elenco dei File";
  $msg['cmdGetFile']    = "Prendi File";
  $msg['cmdRename']     = "Rinomina";
  $msg['cmdDelete']     = "Cancella";
  $msg['cmdEdit']       = "Modifica";
  $msg['cmdChangePerm'] = "Modifica Permessi";
  $msg['cmdFileInfo']   = "Guarda informazioni File";
  $msg['cmdUploadFile'] = "Carica File";
  $msg['cmdChangeDir']  = "Cambia Cartella";
  $msg['cmdParentDir']  = "Cartella Superiore";
  $msg['cmdNewDir']     = "Nuova Cartella";
  $msg['cmdSortAsc']    = "Ordina Crescente";
  $msg['cmdSortDesc']   = "Ordina Decrescente";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Non puoi cambiare i permessi";
  $msg['errDirNew']     = "Errore durante la creazione";
  $msg['errOpen']       = "Errore durante l'apertura";
  $msg['errSave']       = "Errore durante il salvataggio";
  $msg['errDelete']     = "Errore durante la cancellazione";
  $msg['errRename']     = "Errore durante la rinominazione";
  $msg['errDisabled']   = "Questa funzione è disabilitata";
  $msg['errConnect']    = "Nessuna connessione con il server FTP";
  $msg['errLogin']      = "Autenticazione fallita";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Cancellare la cartella in maniera definitiva?";
  $msg['msgDeleteFile'] = "Cancellare il file in maniera definitiva?";
  $msg['msgSaveFile']   = "Salvare il file e sovrascrivendo quello già esistente?";

//========================================================================================================
?>
