<?
/*********************************************************************************************************
 This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Dateiinfo";
  $msg['name']          = "Name";
  $msg['size']          = "Größe";
  $msg['lastChange']    = "Letzte Änderung";
  $msg['owner']         = "Eigentümer";
  $msg['group']         = "Gruppe";
  $msg['other']         = "Andere";
  $msg['read']          = "Lesen";
  $msg['write']         = "Schreiben";
  $msg['execute']       = "Ausführen";
  $msg['permissions']   = "Zugriffsrechte";
  $msg['error']         = "FEHLER";
  $msg['searchResult']  = "Suchergebnis";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Zurücksetzen";
  $msg['cmdSave']       = "Speichern";
  $msg['cmdViewList']   = "Liste anzeigen";
  $msg['cmdGetFile']    = "Datei herunterladen";
  $msg['cmdRename']     = "Umbenennen";
  $msg['cmdDelete']     = "Löschen";
  $msg['cmdEdit']       = "Bearbeiten";
  $msg['cmdChangePerm'] = "Zugriffsrechte ändern";
  $msg['cmdFileInfo']   = "Dateiinfo anzeigen";
  $msg['cmdUploadFile'] = "Datei hochladen";
  $msg['cmdChangeDir']  = "Verzeichnis wechseln";
  $msg['cmdParentDir']  = "Verzeichnis wechseln";
  $msg['cmdNewDir']     = "Neues Verzeichnis";
  $msg['cmdSortAsc']    = "Aufsteigend sortieren";
  $msg['cmdSortDesc']   = "Absteigend sortieren";
  $msg['cmdDetails']    = "Details anzeigen";
  $msg['cmdIcons']      = "Icons anzeigen";
  $msg['cmdSearch']     = "Suchen";
  $msg['cmdGoBack']     = "Zurück";
  $msg['cmdRefresh']    = "Aktualisieren";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Kann Zugriffsrechte nicht ändern";
  $msg['errDirNew']     = "Fehler beim Erstellen";
  $msg['errOpen']       = "Fehler beim Öffnen";
  $msg['errSave']       = "Fehler beim Speichern";
  $msg['errDelete']     = "Fehler beim Löschen";
  $msg['errRename']     = "Fehler beim Umbenennen";
  $msg['errDisabled']   = "Diese Funktion wurde deaktiviert";
  $msg['errConnect']    = "Keine Verbindung zum FTP-Server";
  $msg['errLogin']      = "Login fehlgeschlagen";
  $msg['errAccess']     = "Zugriff verweigert";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Dieses Verzeichnis unwiderruflich löschen?";
  $msg['msgDeleteFile'] = "Diese Datei unwiderruflich löschen?";
  $msg['msgSaveFile']   = "Datei speichern und bestehende überschreiben?";

//========================================================================================================
?>
