<?
/*********************************************************************************************************
 This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Informações do ficheiro";
  $msg['name']          = "Nome";
  $msg['size']          = "Tamanho";
  $msg['lastChange']    = "Última modificação";
  $msg['owner']         = "Proprietário";
  $msg['group']         = "Grupo";
  $msg['other']         = "Outros";
  $msg['read']          = "Lêr";
  $msg['write']         = "Escrever";
  $msg['execute']       = "Executar";
  $msg['permissions']   = "Permissões";
  $msg['error']         = "ERRO";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Anular";
  $msg['cmdSave']       = "Guardar";
  $msg['cmdViewList']   = "Vêr lista";
  $msg['cmdGetFile']    = "Obter ficheiro";
  $msg['cmdRename']     = "Alterar nome";
  $msg['cmdDelete']     = "Apagar";
  $msg['cmdEdit']       = "Editar";
  $msg['cmdChangePerm'] = "Alterar permissões";
  $msg['cmdFileInfo']   = "Vêr informações do ficheiro";
  $msg['cmdUploadFile'] = "Enviar ficheiro";
  $msg['cmdChangeDir']  = "Mudar directoria";
  $msg['cmdParentDir']  = "Directoria ligada";
  $msg['cmdNewDir']     = "Nova directoria";
  $msg['cmdSortAsc']    = "Ordenação ascendente";
  $msg['cmdSortDesc']   = "Ordenação descendente";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Não é possível alterar as permissões";
  $msg['errDirNew']     = "Erro ao criar";
  $msg['errOpen']       = "Erro ao abrir";
  $msg['errSave']       = "Erro ao salvar";
  $msg['errDelete']     = "Erro ao apagar";
  $msg['errRename']     = "Erro ao alterar o nome";
  $msg['errDisabled']   = "Função desactivada pela administração";
  $msg['errConnect']    = "Sem ligação FTP ao servidor";
  $msg['errLogin']      = "Falha ao entrar";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Deseja mesmo remover esta directoria? Não é possível voltar atrás!";
  $msg['msgDeleteFile'] = "Deseja mesmo apagar este ficheiro? Não será possível voltar atrás!";
  $msg['msgSaveFile']   = "Deseja salvar este ficheiro e substituir o actual?";

//========================================================================================================
?>
