<?
/*********************************************************************************************************
 This code is part of the FileManager software (www.gerd-tentler.de/tools/filemanager), copyright by
 Gerd Tentler. Obtain permission before selling this code or hosting it on a commercial website or
 redistributing it over the Internet or in any other medium. In all cases copyright must remain intact.
*********************************************************************************************************/

//========================================================================================================
// General
//========================================================================================================
  $msg['fileInfo']      = "Info súboru";
  $msg['name']          = "Meno";
  $msg['size']          = "Ve¾kos";
  $msg['lastChange']    = "Posledná zmena";
  $msg['owner']         = "Majite¾";
  $msg['group']         = "Skupina";
  $msg['other']         = "Iný";
  $msg['read']          = "Èítaj";
  $msg['write']         = "Zápis";
  $msg['execute']       = "Vykonaj";
  $msg['permissions']   = "Povolenia";
  $msg['error']         = "ERROR";
  $msg['searchResult']  = "Search Result";

//========================================================================================================
// Commands
//========================================================================================================
  $msg['cmdReset']      = "Reset";
  $msg['cmdSave']       = "Ulož";
  $msg['cmdViewList']   = "Pozrie zoznam";
  $msg['cmdGetFile']    = "Získa súbor";
  $msg['cmdRename']     = "Premenova";
  $msg['cmdDelete']     = "Zmaza";
  $msg['cmdEdit']       = "Editova";
  $msg['cmdChangePerm'] = "Zmeni práva";
  $msg['cmdFileInfo']   = "Zobraziž info súboru";
  $msg['cmdUploadFile'] = "Upload súboru";
  $msg['cmdChangeDir']  = "Otvori adresár";
  $msg['cmdParentDir']  = "Základný adresár";
  $msg['cmdNewDir']     = "Nová zložka";
  $msg['cmdSortAsc']    = "Triedi vzostupne";
  $msg['cmdSortDesc']   = "Triedi zostupne";
  $msg['cmdDetails']    = "View Details";
  $msg['cmdIcons']      = "View Icons";
  $msg['cmdSearch']     = "Search";
  $msg['cmdGoBack']     = "Go Back";
  $msg['cmdRefresh']    = "Refresh";

//========================================================================================================
// Error Messages
//========================================================================================================
  $msg['errPermChange'] = "Nemožno zmeni povolenia";
  $msg['errDirNew']     = "Chyba poèas vytvárania";
  $msg['errOpen']       = "Chyba poèas otvárania";
  $msg['errSave']       = "Chyba poèas ukladania";
  $msg['errDelete']     = "Chyba poèas mazania";
  $msg['errRename']     = "Chyba poèas premenovávania";
  $msg['errDisabled']   = "Táto funkcia je obmedzená";
  $msg['errConnect']    = "Žiadne spojenie s FTP serverom";
  $msg['errLogin']      = "Login neúspešný";
  $msg['errAccess']     = "Access denied";

//========================================================================================================
// Other Messages
//========================================================================================================
  $msg['msgRemoveDir']  = "Odstráni túto zložku natrvalo?";
  $msg['msgDeleteFile'] = "Odstráni tento súbor natrvalo?";
  $msg['msgSaveFile']   = "Uloži súbor a prepísa existujúci?";

//========================================================================================================
?>
